---
title: "Pierre-Ami Maudoux's CV"
author: Pierre-Ami Maudoux
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1ZvBze1Di0TIXBg3PieaCr5iR1vaI6u7RNdeLE9yVcdo",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
 cat("[View this CV online with links](https://pamdx.github.io/personal_site/cv.html)")
} else {
 cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/pamdx/cv/raw/main/cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



IT Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the [datadrivencv](https://github.com/nstrayer/datadrivencv) R package.

Last updated on `r format(Sys.time(), "%d/%m/%Y")`.



Main
================================================================================

Pierre-Ami Maudoux {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```



<!-- Research Experience {data-icon=laptop} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('research_positions') -->
<!-- ``` -->



Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

<!-- ::: aside -->
<!-- ```{r} -->
<!-- CV %<>% print_text_block('industy_experience_aside') -->
<!-- ``` -->
<!-- ::: -->

```{r}
CV %<>% print_section('experience')
```

<!-- These breaks just force a new page so section doesn't get cut off -->
<br>
<br>
<br>

Publications {data-icon=newspaper}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('publications')
```

<!-- These breaks just force a new page so section doesn't get cut off -->
<br>
<br>
<br>

Conferences {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('conferences')
```

<!-- These breaks just force a new page so section doesn't get cut off -->
<br>
<br>
<br>

Courses & certifications {data-icon=certificate}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('certifications')
```

<!-- These breaks just force a new page so section doesn't get cut off -->
<br>
<br>
<br>

<!-- Teaching Experience {data-icon=chalkboard-teacher} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ::: aside -->
<!-- ```{r} -->
<!-- CV %<>% print_text_block('teaching_experience_aside') -->
<!-- ``` -->
<!-- ::: -->

<!-- ```{r} -->
<!-- CV %<>% print_section('teaching_positions') -->
<!-- ``` -->



<!-- Selected Data Science Writing {data-icon=chart-line} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ::: aside -->
<!-- ```{r} -->
<!-- CV %<>% print_text_block('data_science_writing_aside') -->
<!-- ``` -->
<!-- ::: -->

<!-- ```{r} -->
<!-- CV %<>% print_section('data_science_writings') -->
<!-- ``` -->



<!-- Selected Press (About)  {data-icon=newspaper} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('about_me_press') -->
<!-- ``` -->


<!-- <br> -->
<!-- <br> -->


<!-- Selected Press (By)  {data-icon=newspaper} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('by_me_press') -->
<!-- ``` -->



<!-- Selected Publications, Posters, and Talks {data-icon=book} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('academic_articles') -->
<!-- ``` -->



```{r}
CV %<>% print_links()
```

